services:
  front-end:
    build:
      context: ./front-end  # front-endのDockerfileがここにある場合
      dockerfile: Dockerfile # 明示的にDockerfileの名前を指定する場合
    ports:
      - "3000:3000"
    volumes:
      - ./front-end:/app
      - /app/node_modules
    command: npm start

  flask_app:
    build:
      context: ./back-end  # back-endのDockerfileがここにある場合
      dockerfile: Dockerfile # 明示的にDockerfileの名前を指定する場合
    volumes:
      - ./back-end:/app
    working_dir: /app
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: /bin/sh -c "flask db upgrade && flask run --host=0.0.0.0"  # マイグレーション後にアプリケーションを起動
    depends_on:
      - db

  back-end:
    build:
      context: ./back-end  # back-endのDockerfileがここにある場合
    ports:
      - "5002:5002"
    volumes:
      - ./back-end:/app
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: python app.py
    depends_on:
      - db
    env_file:
      - .env.docker

  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  db-data:
