version: '3.8'

services:
  front-end:
    build:
      context: ./front-end
    ports:
      - "3000:3000"
    volumes:
      - ./front-end:/app
      - /app/node_modules
    command: npm start

  back-end:
    build:
      context: ./back-end
    ports:
      - "5002:5002"
    volumes:
      - ./back-end:/app
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: python app.py
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  db-data:
